// action types

export const FETCH_PARCELS_LIST = 'FETCH_PARCELS_LIST';
export const FETCH_PARCELS_SUCCESS = 'FETCH_PARCELS_SUCCESS';

export const FETCH_DELIVERIES_LIST = 'FETCH_DELIVERIES_LIST';
export const FETCH_DELIVERIES_SUCCESS = 'FETCH_DELIVERIES_SUCCESS';

export const REMOVE_PARCEL = 'REMOVE_PARCEL';
export const REMOVE_PARCEL_SUCCESS = 'REMOVE_PARCEL_SUCCESS';
export const SHOW_PARCEL_INFO = 'SHOW_PARCEL_INFO';
