// action types
export const INITIALIZE = 'INITIALIZE';
export const IS_AUTHORIZED = 'IS_AUTHORIZED';
export const AUTHORIZATION_SUCCESS = 'AUTHORIZATION_SUCCESS';
export const AUTHORIZATION_FAILURE = 'AUTHORIZATION_FAILURE';
export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';

// auth statuses
export const PENDING_USER_VERIFICATION = 'PENDING_USER_VERIFICATION';
export const AUTHORIZED = 'AUTHORIZED';
export const UNAUTHORIZED = 'UNAUTHORIZED';
