// fetch
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

// create
export const SHOW_CREATE_USER_COMPONENT = 'SHOW_CREATE_USER_COMPONENT';
export const CLOSE_CREATE_USER_COMPONENT = 'CLOSE_CREATE_USER_COMPONENT';

export const CREATE_USER = 'CREATE_USER';
export const USER_CREATED = 'USER_CREATED';

// edit
export const SHOW_EDIT_USER_COMPONENT = 'SHOW_EDIT_USER_COMPONENT';
export const EDIT_USER = 'EDIT_USER';
export const USER_EDITED = 'USER_EDITED';
export const CANCEL_EDIT_USER = 'CANCEL_EDIT_USER';

export const PREPARE_USER_TO_CHANGE_STATUS = 'PREPARE_USER_TO_CHANGE_STATUS';
export const CONFIRM_CHANGE_STATUS_OF_USER = 'CONFIRM_CHANGE_STATUS_OF_USER';
export const USER_STATUS_CHANGED = 'USER_STATUS_CHANGED';

export const CHANGE_USER_STATUS_ACTION_ENABLE = 'enable';
export const CHANGE_USER_STATUS_ACTION_DISABLE = 'disable';

export const PREPARE_STATE_FOR_MANAGING_SUBORDINATES = 'PREPARE_STATE_FOR_MANAGING_SUBORDINATES';
export const STORE_SUBORDINATES = 'STORE_SUBORDINATES';
export const SUBMIT_NEW_SUPERVISOR = 'SUBMIT_NEW_SUPERVISOR';
export const NEW_SUPERVISOR_SAVED = 'NEW_SUPERVISOR_SAVED';

export const SHOW_USER_PROFILE = 'SHOW_USER_PROFILE';
export const SHOW_USER_PROFILE_SUCCESS = 'SHOW_USER_PROFILE_SUCCESS';
